name: 'Amazon ECS Deploy Action'
description: 'Deploy a Docker image to Amazon ECS from GitHub Actions'
inputs:
  service-name:
    description: 'The name of the service being deployed. This will be used to derive ECR repository, ECS service, and task role.'
    required: true
  aws-ecs-cluster:
    description: 'The AWS ECS cluster name where the service will be deployed.'
    required: true
  aws-region:
    description: 'The AWS region where the ECS service is located.'
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        echo "Reusing deploy steps from ecs-deploy.yml"
      shell: bash
      working-directory: .github/actions/ecs-deploy.yml
