name: CD - Deploy to ECS

on:
  workflow_call:
    inputs:
      stack-name:
        required: true
        type: string
        description: 'Nome da stack do CloudFormation'
      AWS_REGION:
        required: true
        type: string
      ImageUrl:
        required: true
        type: string
        description: 'URL da imagem Docker no ECR'
    secrets:
      AWS_ACCOUNT_ID:
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Load CloudFormation template
        run: |
          if [ ! -f template.json ]; then
            echo "Arquivo template.json não encontrado no repositório da action"
            exit 1
          fi

      # Passo 3: Deploy no ECS via CloudFormation usando template.json
      - name: Deploy to ECS using CloudFormation
        uses: aws-actions/aws-cloudformation-deploy-action@v1
        with:
          stack-name: ${{ inputs.stack-name }}
          template-file: 'template.json'
          parameter-overrides: |
            ImageUrl=${{ inputs.ImageUrl }}
          aws-region: ${{ inputs.AWS_REGION }}
          capabilities: CAPABILITY_NAMED_IAM
